function cast(Caster, Target, Agi, AttackSpeed, MoveSpeed, BaseAvoidance, PhysMit, SpellMit)
  AddSpellBonus(Caster, 2, Agi)
  AddSpellBonus(Caster, 617, AttackSpeed)
  AddSpellBonus(Caster, 616, MoveSpeed)
  AddSpellBonus(Caster, 696, BaseAvoidance)
  AddSpellBonus(Caster, 204, PhysMit)
  AddSpellBonus(Caster, 201, SpellMit)
  AddSpellBonus(Caster, 202, SpellMit)
  AddSpellBonus(Caster, 203, SpellMit)
end