function cast(Caster, Target, MaxHP, Offensive, ResistAmt)
  AddSpellBonus(Target, 500, MaxHP)
  AddSkillBonus(Target, GetSkillIDByName("Crushing"), Offensive)
  AddSkillBonus(Target, GetSkillIDByName("Piercing"), Offensive)
  AddSkillBonus(Target, GetSkillIDByName("Slashing"), Offensive)
  AddSkillBonus(Target, GetSkillIDByName("Ranged"), Offensive)
  AddSpellBonus(Caster, 201, ResistAmt)
  AddSpellBonus(Caster, 202, ResistAmt)
  AddSpellBonus(Caster, 203, ResistAmt)
end
